name: flutter_in_app_browser
description: "A lightweight, customizable in-app browser for Flutter. This package provides a native-feeling, Instagram-style browser experience with smooth animations, gesture controls, and a modern UI—all without external dependencies."
version: 0.0.1
homepage: https://nocorps.org/
repository: https://github.com/KANAGARAJ-M/in_app_browser
issue_tracker: https://github.com/KANAGARAJ-M/in_app_browser/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 
  share_plus: 
  clipboard: 
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nocorps.flutter_in_app_browser
        pluginClass: InAppBrowserPlugin
